-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS reviews
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    rating integer NOT NULL,
    date text NOT NULL,
    summary text NOT NULL,
    body text NOT NULL,
    recommend boolean NOT NULL,
    reported boolean NOT NULL,
    reviewer_name text NOT NULL,
    reviewer_email text NOT NULL,
    response text,
    helpfulness integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS photos
(
    id integer NOT NULL,
    review_id integer NOT NULL,
    url text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS meta
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS meta_data
(
    cid integer NOT NULL,
    characteristic_id integer NOT NULL,
    review_id integer NOT NULL,
    value text NOT NULL,
    PRIMARY KEY (cid)
);

ALTER TABLE IF EXISTS photos
    ADD FOREIGN KEY (review_id)
    REFERENCES reviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS meta
    ADD FOREIGN KEY (id)
    REFERENCES meta_data (cid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS meta_data
    ADD FOREIGN KEY (review_id)
    REFERENCES reviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;